### ISSUE TITLE
[enhancement] e2e usage example

### ISSUE THREAD

**Issue by kadosh1000** [fulls1z3/ngx-cache#10]
**I'm submitting a ...**
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[X] Documentation issue or request
```
**The request:**
I could not find in the documentation or in the angular-universal seed project any example of how to get / set values to the localStorage, cookies, etc...
Would love to get a full e2e example of usage.

**Environment**
* **Angular version:** 4.3.3

* **For Tooling issues:**
- Node version: 7.9.0
- Platform:  Windows

**Comment by fulls1z3** [comment]
Closing in favor of #14
