### ISSUE TITLE
Cache.has does not check if item in cache is expired

### ISSUE THREAD

**Issue by davija** [fulls1z3/ngx-cache#125]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Support request =>
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
When calling ```Cache.has('someKey')``` it only looks if the key exists, not if it has expired.

**Expected/desired behavior**
If the item in the cache has expired then the ```Cache.has``` method should not say it exists.

**Minimal reproduction of the problem with instructions**
- Add item to cache with short TTL (e.g.; 1-2 seconds) ```Cache.set('someKey', { test: 123 }, null, 2)```
- Wait for the allotted time has passed
- Call ```Cache.has('someKey')```

**What is the motivation / use case for changing the behavior?**
If ```Cache.has('someKey')``` says it has something for that key, it shouldn't return undefined when I call ```Cache.get('someKey')```.

**Environment**
***Angular version:** 7.x

***Browser:**
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by fulls1z3** [comment]
@davija thanks for bringing this, and i appreciate your attention to details. and sorry for the delay :)

yes, that's an edge case i didn't figure out when this library was initially built. are you able to come up with a PR which fixes this - otherwise i'll need to do it in a way as time allows.
