### ISSUE TITLE
run time errors when building using ivy

### ISSUE THREAD

**Issue by deefactorial** [fulls1z3/ngx-cache#127]
**I'm submitting a ...**  (check one with "x")
```
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

In angular 8 when I turn on 
```
"angularCompilerOptions": { 
        "enableIvy": true 
    },
```
I get the following errors in the console:
```
zone.js:699 Unhandled Promise rejection: Can't resolve all parameters for MemoryCacheService: (?). ; Zone: <root> ; Task: Promise.then ; Value: Error: Can't resolve all parameters for MemoryCacheService: (?).
    at getUndecoratedInjectableFactory (core.js:11579) [angular]
    at injectableDefOrInjectorDefFactory (core.js:11569) [angular]
```
**Expected/desired behavior**

there should not be any console errors
**Minimal reproduction of the problem with instructions**

Import:
```
        BrowserCacheModule.forRoot([
            {
                provide: CACHE,
                useClass: MemoryCacheService
            }
        ]),
```
compie app using ivy and see run time errors.

**What is the motivation / use case for changing the behavior?**

Upgrading to Ivy, it's the default in angular 9.

**Environment**
* **Angular version:** 8.2.14

* **Browser:**
- [x] Chrome (desktop) Version 79.0.3945.130 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 10.16.3
- Platform:  Linux

* Others:

**Comment by lucianot54** [comment]
I migrated my application with Angular 9 and I have the same error.

**Comment by fulls1z3** [comment]
https://github.com/fulls1z3/ngx-cache/issues/128#issuecomment-590959193
