### ISSUE TITLE
Angular 9 + Ivy 

### ISSUE THREAD

**Issue by joejordanbrown** [fulls1z3/ngx-cache#128]
@fulls1z3

Thanks for the great project.

Have you started any of the work for this to work with Angular Ivy?

If not I could create a pull request, it's only a handful of small changes for it to work.

We've already done this locally because the `ngx-cache` package was a blocker on updating our projects. We've made all the changes required for it to work with Ivy but included the source directly as an angular CLI library in our project, using Angular CLI to build the library which is just a wrapper around `ng-packagr`.

Let me know, and I'll merge our changes into your repo using your current build setup.

**Comment by makulatura** [comment]
@joejordanbrown could you elaborate please, because I have an ngx-cache issue when upgrading to 9.
"Can't resolve all parameters for MemoryCacheService"

**Comment by ica4c** [comment]
@makulatura Solved by directly referencing deps of provider 

`
{
       provide: CACHE,
        useClass: (MemoryCacheService),
        deps: [PLATFORM_ID]
}
`
