### ISSUE TITLE
Error: Can't resolve all parameters for MemoryCacheService

### ISSUE THREAD

**Issue by kandalfe** [fulls1z3/ngx-cache#132]
[ ] Regression
[ ] Bug report
[ x] Support request

**Current behavior**
Hello,
I'm compiling my angular application with ivy, angular 9.
And, using MemoryCacheService from @ngx-cache/platform-browser, when I start the application, the browser console says : 
Error: Can't resolve all parameters for MemoryCacheService

**Expected/desired behavior**
It works fine when I don't compile with ivy.

**Minimal reproduction of the problem with instructions**

Here's my app.module : 
```

import { CacheModule, CacheLoader, CacheStaticLoader, CACHE } from '@ngx-cache/core';
import { BrowserCacheModule, LocalStorageCacheService , MemoryCacheService } from '@ngx-cache/platform-browser';
...

export function cacheFactory(): CacheLoader {
  return new CacheStaticLoader({
    key: 'NGX_CACHE',
    lifeSpan: {
      expiry: null,
      TTL:  86400
    }
  });
}

@NgModule({
imports: [
BrowserCacheModule.forRoot([
      {
        provide: CACHE,
        useClass: MemoryCacheService // or, LocalStorageCacheService
      }
    ]),
}),
    CacheModule.forRoot({
      provide: CacheLoader,
      useFactory: (cacheFactory)
    }),
]
```

**Environment**
* **Angular version:** 9.1.1

* **Browser:**
- [x ] Chrome (desktop) version 80.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 10  
- Platform:  Windows

Thank you very much!!

**Comment by gcoppe** [comment]
Hello,

Same issue with my project. Trying to migrate from Angular 8 to Ang9 using ivy. 
Same error when using LocalStorageCacheService instead of MemoryCacheService

**Comment by fortex** [comment]
I've got the same problem. Also after upgrading from ng8 to ng9 using ivy.

I fixed it for now by implementing my own storage using the Cache interface.

**Comment by alecrt** [comment]
Same problem here

**Comment by fulls1z3** [comment]
https://github.com/fulls1z3/ngx-cache/issues/128
