### ISSUE TITLE
V9 ngx-cache-core.js exiting with error

### ISSUE THREAD

**Issue by XenoStrat** [fulls1z3/ngx-cache#135]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
Execution Error; file ngx-cache-core.js (in core/fesm5), line 101
  ```
  CacheService.prototype.getWithMetadata = function (key) {
        var normalized = CacheService.normalizeKey(key);
        var cached = this.cache.getItem(normalized);
101->if (Object.entries(cached).length !== 0 && cached.constructor === Object) {
            if (CacheService.validateValue(cached)) {
                return cached;
            }
            this.remove(key);
        }
        return undefined;
    };
```
**cached is undefined because this.cache.getItem(normalized); returns undefined when the key does not exist in cache, thus makes an error on Object.entries(cached).length !== 0 in angular v9 (cannot convert undefined to object)
there was no problem on angular v8; it appeared after upgrading.

**Expected/desired behavior**
Changing the line to:
 ```       if (cached && Object.entries(cached).length !== 0 && cached.constructor === Object) {```
works perfectly here.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
doesn't work without this change on my side.

**Environment**
* **Angular version:** 9.1.12

* **Browser:**
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 12.18.4
- Platform:  Windows server 2012R2 (win32 x64)

* Others:
Not sure how hard it would be to upgrade this project to be used with subsequent angular versions as I'm pretty new in this area but I'm thinking of trying for educational purpose; I would like to upgrade my project at least to angular 10. Unless you plan to make a new version soon?

**Comment by fulls1z3** [comment]
see https://github.com/fulls1z3/ngx-cache/pull/141
